#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "navidrome"
}


config_cb() {
        [ $# -eq 0 ] && return

        option_cb() {
                local option="$1"
                local value="$2"
                eval $option=$value
        }

        list_cb() {
                local name="$1"
                local value="$2"
        }
}


start_service() {
	# Options with default value different with the syncthing should be defined explicitly here
	local enabled=0
	local user="navidrome"
	local prog="/usr/bin/navidrome"

	local datafolder="/etc/navidrome"
	local config="${datafolder}/navidrome.toml"
	local musicfolder="/music"
        local imagecachesize="0"
        local transcodingcachesize="0"
        local port="4533"
        local loglevel="info"
        local use_bg="0"
        local use_bg_path="/etc/navidrome/bg.jpg"
	local enabletranscodingconfig="0"

	config_load "navidrome"        
	local config="${datafolder}/navidrome.toml"

	# Some of the default values below might not match the defaults
	#   in /etc/config/syncthing: the reason is to remain backwards
	#   compatible with the older versions of this service as it
	#   evolves.
	[ "$enabled" -gt 0 ] || return 0

	[ -d "$datafolder" ] || mkdir -p "$datafolder"
	# A separate step to handle an upgrade use case
	[ -d "$datafolder" ] && chown -R $user:$user "$datafolder"
	[ -f "$config" ]  || touch "$config"
	[ -f "$config" ] && chown $user:$user "$config"
	
	procd_open_instance
	procd_set_param command "$prog"
	procd_append_param command --configfile "$config"
	procd_append_param command --datafolder "$datafolder"
	procd_append_param command --musicfolder "$musicfolder"
	procd_append_param command --imagecachesize "${imagecachesize}MB"
	procd_append_param command --transcodingcachesize "${transcodingcachesize}MB"
	procd_append_param command --loglevel "$loglevel"
	procd_append_param command --port "$port"
	[ "$use_bg" -eq 1 ] && procd_append_param command --uiloginbackgroundurl "$use_bg_path"
	[ "$enabletranscodingconfig" -eq 1 ] && procd_append_param command --enabletranscodingconfig
	

	procd_set_param term_timeout 15
	procd_set_param user "$user"
	procd_set_param respawn
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
